
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs';
import MainNavbar from "@/components/MainNavbar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY} dynamic>
        
        <body>
          <MainNavbar/>
          {children}
        </body>
      </ClerkProvider>
    </html>
  );
}

